// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxjW7EnYJ2vMXgvC9zMtVYs6uoQKbovKM',
    appId: '1:861320968820:web:ab4939e46edf269ced6f21',
    messagingSenderId: '861320968820',
    projectId: 'awd-irrigation',
    authDomain: 'awd-irrigation.firebaseapp.com',
    databaseURL: 'https://awd-irrigation-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'awd-irrigation.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHrKFDE0mwQf01Syjhchv_Jjo9Yle_gLY',
    appId: '1:861320968820:android:9446361bf136d0d6ed6f21',
    messagingSenderId: '861320968820',
    projectId: 'awd-irrigation',
    databaseURL: 'https://awd-irrigation-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'awd-irrigation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz-kPfx0x74vqSiCMh84EVXxeU1PDSxhw',
    appId: '1:861320968820:ios:6b5e41ea8ae9ddb1ed6f21',
    messagingSenderId: '861320968820',
    projectId: 'awd-irrigation',
    databaseURL: 'https://awd-irrigation-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'awd-irrigation.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz-kPfx0x74vqSiCMh84EVXxeU1PDSxhw',
    appId: '1:861320968820:ios:6b5e41ea8ae9ddb1ed6f21',
    messagingSenderId: '861320968820',
    projectId: 'awd-irrigation',
    databaseURL: 'https://awd-irrigation-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'awd-irrigation.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxjW7EnYJ2vMXgvC9zMtVYs6uoQKbovKM',
    appId: '1:861320968820:web:268670982d83a27bed6f21',
    messagingSenderId: '861320968820',
    projectId: 'awd-irrigation',
    authDomain: 'awd-irrigation.firebaseapp.com',
    databaseURL: 'https://awd-irrigation-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'awd-irrigation.firebasestorage.app',
  );
}
